[server]
# Python s端r端m端n端 3.11 olarak belirt
pythonVersion = "3.11"

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 